version: '3'

services:
  app:
    image: 'kotlin-bank:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - DB_HOST=db
    ports:
      - "8081:8081"

  db:
    image: 'postgres:15.4-bullseye'
    container_name: db
    environment:
      - POSTGRES_USER=kotlinBank
      - POSTGRES_PASSWORD=kotlinBank
      - TZ=Asia/Seoul
    ports:
      - "5432:5432"